### ISSUE TITLE
Tentative title & table of contents

### ISSUE THREAD

**Issue by rrrlw** [rrrlw/tda-book#1]
Currently, the repo contains the Rstudio bookdown template. Would be nice to have a non-bookdown plaintext file that contains a table of contents or book outline to guide writing/planning. Don't need a final TOC to close the issue, but at least somewhat of a plan.

**Comment by rrrlw** [comment]
Added an incomplete skeleton (table-of-contents.md). What do you think, @corybrunson?

**Comment by corybrunson** [comment]
The internal structure of each method chapter makes sense, though they might change as the chapters take shape. It's a good substrate to start from, i think. My outlook is to include at least a minimum of exercises in each but to allow the exercise sections to grow as readers and potentially students put them to use on open-access real-world data sets.

**Comment by rrrlw** [comment]
I agree, regarding the likely evolution the tentative TOC will undergo and the min exercises per section. Since it seems like we have a skeleton outline, I’ll close this issue shortly, but feel free to further edit TOC and we can keep adding chapter files as we write. Does that sound okay?

**Comment by corybrunson** [comment]
Sounds OK!
